# Generated by Django 3.1.14 on 2022-01-14 10:49

import django.db.models.deletion

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Author name")),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Birthday"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Author's nationality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("PL", "Polish"),
                            ("FR", "French"),
                            ("DE", "German"),
                        ],
                        default="EN",
                        max_length=2,
                    ),
                ),
                ("pages", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FANTASY", "Fantasy"),
                            ("NOVEL", "Novel"),
                            ("COOKBOOK", "Cookbook"),
                            ("BIOGRAPHY", "Biography"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.author",
                    ),
                ),
            ],
            options={
                "unique_together": {("author", "title", "language")},
            },
        ),
    ]
