# Generated by Django 2.2.6 on 2019-10-30 08:28

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Author name")),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Birthday"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Author's nationality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("pl", "Polish"),
                            ("fr", "French"),
                            ("de", "German"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("pages", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (None, "N/A"),
                            ("fantasy", "Fantasy"),
                            ("novel", "Novel"),
                            ("cookbook", "Cookbook"),
                            ("biography", "Biohgraphy"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.Author",
                    ),
                ),
            ],
        ),
    ]
